version: '3.8'
services:
  jobs_db:
    image: mongo
    container_name: jobs_db
    command: --auth
    ports:
      - 27017-27019:27017-27019
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
    secrets:
      - mongodb_root_password
      - mongodb_root_username
    volumes:
      - './mongodb/data:/data/db'

secrets:
  mongodb_root_password:
    file: mongodb/.mongodb_root_password
  mongodb_root_username:
    file: mongodb/.mongodb_root_username
