#!/bin/bash

MONGO_ROOT_USER="$MONGO_INITDB_ROOT_USERNAME"
MONGO_ROOT_PASS="$MONGO_INITDB_ROOT_PASSWORD"
FLASK_USER=`cat $MONGO_FLASK_USERNAME_FILE`
FLASK_PASS=`cat $MONGO_FLASK_PASSWORD_FILE`

mongo -- admin <<EOF
const MONGO_INITDB_ROOT_USERNAME = '$MONGO_ROOT_USER';
const MONGO_INITDB_ROOT_PASSWORD = '$MONGO_ROOT_PASS';
const MONGO_DATABASE = '$MONGO_DATABASE';
const FLASK_USERNAME = '$FLASK_USER';
const FLASK_PASSWORD = '$FLASK_PASS';
db.auth(MONGO_INITDB_ROOT_USERNAME, MONGO_INITDB_ROOT_PASSWORD);
var db = db.getSiblingDB(MONGO_DATABASE)
db.createUser({user: FLASK_USERNAME, pwd: FLASK_PASSWORD, roles: [{role: 'readWrite', db: MONGO_DATABASE}]});
EOF
